name: Docker Image CI

on:
  workflow_dispatch:
  #push:
  #  branches: [ main ]
  #pull_request:
  #  branches: [ main ]

env:
  IMG_NAME: svasek/php-fpm
  REGISTRY: docker.io
  
jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ github.actor }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag $IMG_NAME:build
    
    - name: Tag and Push the Image
      run: |
        # Get PHP release version
        PHPVERSION=$(docker inspect --format '{{ index .Config.Labels "php.version"}}' ${IMG_NAME}:build)
        PHPMINOVER=$(echo ${PHPVERSION} | cut -d . -f 1,2)
        PHPMAJOVER=$(echo ${PHPVERSION} | cut -d . -f 1)
        # Change all uppercase to lowercase
        IMG_NAME=$(echo $IMG_NAME | tr '[A-Z]' '[a-z]')
        # Strip git ref prefix from version
        VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
        # Strip "v" prefix from tag name
        [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')
        # Use Docker `latest` tag convention
        [ "$VERSION" == "main" ] && VERSION=latest
        echo IMG NAME=$IMG_NAME
        echo VERSION =$VERSION
        echo PHP VERSION=$PHPVERSION
        # Add Tags
        docker tag $IMG_NAME:build $IMG_NAME:${PHPVERSION}
        docker tag $IMG_NAME:build $IMG_NAME:${PHPMAJOVER}
        docker tag $IMG_NAME:build $IMG_NAME:${PHPMINOVER}
        docker tag $IMG_NAME:build $IMG_NAME:$VERSION
       
        # Push the Image
        docker push $IMG_NAME:$VERSION
        docker push $IMG_NAME:${PHPVERSION}
        docker push $IMG_NAME:${PHPMAJOVER}
        docker push $IMG_NAME:${PHPMINOVER}
